name: Release workflow
on:
  push:
    tags:
      - 'v*'
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        env:
          GO111MODULE: on
        with:
          go-version: '1.13'
      - name: Run tests
        run: make ci-test
        env:
          GO111MODULE: on
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
